### ISSUE TITLE
Feature Request: Allow piping input and output from and to stdin/stdout

### ISSUE THREAD

**Issue by errhammr** [spieglt/Cloaker#10]
At the moment it is only possible to read input files that are on the harddrive and save the output to another file on the harddrive. It would be really handy to be able to pipe the input and output to make chaining commands easier.

**Comment by spieglt** [comment]
I've thought about this, I guess I could just take the password as another flag in that case?

**Comment by errhammr** [comment]
The flag and password can be viewed in (h)top and other tools. Maybe have a CLI flag for the password and as an alternative a second flag to read the password from a file.

17.03.2021 00:38:51 Theron Spiegl ***@***.***>:

**Comment by spieglt** [comment]
It was a little trickier than expected, but version 4 is up on the [releases](https://github.com/spieglt/cloaker) and has flags for stdin, stdout, passwords, and password files! Please try it out and let me know.
