### ISSUE TITLE
Cloaker.run will not install on Linux

### ISSUE THREAD

**Issue by Jack15911** [spieglt/Cloaker#13]
This is a copy of my failed attempt to install Cloaker on Pop-OS 22.04 LTS Linux running on my 12-year-old Gateway:

"jw@pop-os:~/Downloads$ chmod +x cloaker_linux.run
jw@pop-os:~/Downloads$ ./cloaker_linux.run
./cloaker_linux.run: error while loading shared libraries: libicui18n.so.66: cannot open shared object file: No such file or directory
jw@pop-os:~/Downloads$ sudo ./cloaker_linux.run
[sudo] password for jw: 
./cloaker_linux.run: error while loading shared libraries: libicui18n.so.66: cannot open shared object file: No such file or directory
jw@pop-os:~/Downloads$"

If I haven't done this right, please include the right way to do it in the readme.

**Comment by spieglt** [comment]
Sorry, I haven't built or tested it on Pop-OS. Looks like you may be able to run `apt install libicu66` to fix the missing library, but there may be others. If you can send the output of `ldd ~/Downloads/cloaker_linux.run` that will show which are missing. Otherwise there would probably have to be a version built on Pop-OS or you can use the CLI version. I can maybe build a version on Pop-OS but not sure when.

**Comment by spieglt** [comment]
Ah actually I only see `libicu67:amd64 67.1-7ubuntu1` and `libicu70:amd64 70.1-2` for Pop-OS 22...

**Comment by spieglt** [comment]
I'm going to look into packaging it as an AppImage, which should run on a much wider range of distros.

**Comment by spieglt** [comment]
Not perfect, doesn't have an icon, but easier than expected. @Jack15911 please try running `Cloaker.AppImage` on the [releases](https://github.com/spieglt/Cloaker/releases/tag/v4.0) page. I tested it on Pop!_OS 22 and it worked, and should work on many more distros. Thanks for the feedback.

**Comment by Jack15911** [comment]
It worked fine. Actually, I forgot to put underscores between the the words in filename, but it worked anyway. That's better than I expected. Thanks.

**Comment by spieglt** [comment]
Great to hear, thanks for confirming.
