### ISSUE TITLE
Crashes when using custom file decryption path (Linux)

### ISSUE THREAD

**Issue by logix2** [spieglt/Cloaker#2]
Using Linux (Ubuntu 19.04) and Cloaker 2.0 (precompiled binary), when I want to decrypt a file using the GUI, if I try to select "/" or "Computer" as the path, or if I try to enter some path manually, the application crashes with:

```
 ./Cloaker.run 
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
Case insensitive sorting unsupported in the posix collation implementation
Numeric mode unsupported in the posix collation implementation
Case insensitive sorting unsupported in the posix collation implementation
Numeric mode unsupported in the posix collation implementation
Case insensitive sorting unsupported in the posix collation implementation
Numeric mode unsupported in the posix collation implementation
Segmentation fault (core dumped)
```

**Comment by spieglt** [comment]
That's strange, I'll look into why that might be though I'm not sure right now. It works on my Ubuntu 19.04 machine which is not the one it was compiled with. Are you using GNOME?

**Comment by logix2** [comment]
Yes, I'm using GNOME. Interesting. I'll also give it a try on another computer to see if I can replicate this.

**Comment by logix2** [comment]
By the way, this happens every single time on this machine (same as my original bug report), though when I ran it right now it showed a somewhat different output:

```
$ ./Cloaker.run 
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
Case insensitive sorting unsupported in the posix collation implementation
Numeric mode unsupported in the posix collation implementation
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setCompositionMode: Painter not active
QPainter::end: Painter not active, aborted
Case insensitive sorting unsupported in the posix collation implementation
Numeric mode unsupported in the posix collation implementation
Segmentation fault (core dumped)
```

**Comment by spieglt** [comment]
It's definitely a Qt error but it's just using a standard file dialog when prompting for output file location so it's strange that it would crash there. Will you please send the output of `$ ldd ./Cloaker.run`?

**Comment by logix2** [comment]
```
$ ldd ./Cloaker.run
	linux-vdso.so.1 (0x00007ffd30dc4000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f0bceada000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f0bce8d0000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007f0bce8c5000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007f0bce6aa000)
	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f0bce669000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0bce663000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f0bce64e000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f0bce608000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f0bce54d000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f0bce4fe000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f0bce4f9000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f0bce4d0000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f0bce394000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0bce246000)
	libEGL.so.1 => /usr/lib/x86_64-linux-gnu/libEGL.so.1 (0x00007f0bce231000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0bce215000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f0bce0f4000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f0bce060000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0bce03d000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0bcde5b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0bcde41000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0bcdc56000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0bcfc46000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f0bcdc4d000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f0bcdc33000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f0bcdbf4000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f0bcdbbd000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f0bcdb1f000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f0bcd91b000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f0bcd715000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f0bcd656000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f0bcd5e2000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f0bcd5ae000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0bcd5a3000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f0bcd57c000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f0bcd54b000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f0bcd42e000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f0bcd40b000)
```

**Comment by logix2** [comment]
I just tried it on a different computer running Ubuntu 19.04. What's interesting is that all paths except "Computer" are disabled in the "Save decrypted file" dialog, while on my Ubuntu 19.04 they are not.

On this second system, Cloaker froze while clicking through this "Save decrypted file" dialog. Before this I saw some "QPixmap::scaleWidth: Pixmap is null pixmap" errors.

**Comment by spieglt** [comment]
Okay thanks. I also see items in the sidebar greyed out when using it on Ubuntu, but it allows me to navigate with the keyboard or manually enter paths without crashing. I have to go now but will look into this and the other issue more soon. Apologies for the inconvenience and thanks for the helpful feedback.

**Comment by logix2** [comment]
Thanks, and don't worry about it! Bugs happen :)

**Comment by spieglt** [comment]
The version of the Linux GUI on the Releases page was made on Mint 19, so I'm going to compile Qt statically on my Ubuntu machine and see if a binary made with it works any better. I'll post here when it's ready.

**Comment by spieglt** [comment]
I just added a file to the Releases page called `cloakerUbuntu.zip` compiled on Ubuntu. Please give that a try when you get a chance.

**Comment by logix2** [comment]
Unfortunately I still get a segfault:

```
$ ./cloakerUbuntu.run 
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
Case insensitive sorting unsupported in the posix collation implementation
Numeric mode unsupported in the posix collation implementation
Case insensitive sorting unsupported in the posix collation implementation
Numeric mode unsupported in the posix collation implementation
Segmentation fault (core dumped)
```

**Comment by logix2** [comment]
By the way, when I clicked on an item in the sidebar, I got this, maybe it helps:

```
Empty filename passed to function
```

**Comment by logix2** [comment]
Another thing I just noticed: the up / back / etc. icons are missing from the file dialog. It shows as if there was nothing there, that's why I didn't notice until now, but the buttons are clickable.

**Comment by spieglt** [comment]
Okay, I'm experiencing the same error now using the Ubuntu version on Mint. Will look into it more soon.

**Comment by logix2** [comment]
Great, at least you can reproduce it now. Thanks for your work and time!

**Comment by spieglt** [comment]
Seems to be related to:
https://bugreports.qt.io/browse/QTBUG-67866
https://bugreports.qt.io/browse/QTBUG-36657
I saw another link I've since lost saying that you can't use the native dialogs when linking Qt statically but I'm not sure. The dialog works properly and looks different when compiling with the standard Qt installation.

**Comment by logix2** [comment]
Hmm in that case maybe the binary should be distributed differently on Linux? AppImage seems to be a nice alternative - I see [Ksnip](https://github.com/DamirPorobic/ksnip), a Qt app which is available as an AppImage uses native dialogs on Gnome somehow. [Krita](https://krita.org/en/post-download-page/) is another Qt app available as an AppImage and it has a working Qt file dialog. Just an idea...

**Comment by spieglt** [comment]
Yeah, AppImage is what I was thinking. But asked StackOverflow for help in case anyone knows how to do this as I'm pretty stumped. https://stackoverflow.com/questions/56909597/file-dialogs-crash-when-compiling-with-static-version-of-qt

**Comment by spieglt** [comment]
I think I got it! Going to do some more testing before making another release but I think I'd just built the static Qt incorrectly. New command that seems to show the proper dialog and icons:
```~/Qt/5.13.0/Src/configure -static -release -opensource -confirm-license -prefix ~/qt-static/install -no-compile-examples -nomake examples -skip webengine -no-openssl -fontconfig -ico -gif -gtk```

**Comment by spieglt** [comment]
Okay, please download the current `cloakerLinux.zip` on the Releases page and let me know if it's fixed. That binary was still compiled on Mint but it's working with the proper icons and functioning file dialog on my Ubuntu 19.04 machine.

**Comment by spieglt** [comment]
@logix2 I assume you get notified about these comments, but tagging you just in case. I'm closing this issue as I believe it's resolved, but please let me know if you have the chance to retest.

**Comment by logix2** [comment]
Yes, it is working without any issues now. Thank you!
