### ISSUE TITLE
File encrypted with Cloaker GUI can't be decrypted by Cloaker CLI (Linux)

### ISSUE THREAD

**Issue by logix2** [spieglt/Cloaker#3]
A file I encrypted using Cloaker GUI (version 2.0 - I used the precompiled binary) can't be decrypted using Cloaker CLI (version 2.0 - I compiled the binary myself since the precompiled binary doesn't seem to include the CLI).

I'm using Ubuntu 19.04.

**Comment by spieglt** [comment]
Hmm, sorry to hear that. I just encrypted a file with the GUI on Ubuntu 19 and then decrypted with the CLI, and wasn't able to replicate the error. The GUI reports that it encrypts successfully? What error message does the CLI give when decrypting? And you're using the `-d` flag to decrypt in a command like `$ ./cloaker -d ~/encrypted_file.cloaker`?

**Comment by logix2** [comment]
Here's how I used it and the output:

```
$ ./cloaker_cli -d /home/logix/***********.cloaker
Password: 
Error: Incorrect password
```

The GUI is able to decrypt the same file using the same password I used with the CLI.

**Comment by spieglt** [comment]
My only thought so far on this is that maybe your terminal behaves differently from mine and the `rpassword` library is not stripping the newline or something as a result. I just pushed a branch called `no_rpassword` that just uses `stdin().read_line()` and then strips the whitespace, meaning your password will show up in the terminal. Do you mind giving that a try, and maybe pasting from the clipboard in both the GUI and CLI to make sure the password is the same?

**Comment by logix2** [comment]
It worked with the no_rpassword branch!

**Comment by spieglt** [comment]
Great news, thanks for following up. I'll read the `rpassword` source and possibly swap it out for something else in the near future.

**Comment by spieglt** [comment]
Another thought on this: I may not have been using the proper function from `rpassword`. Will you please try the current CLI on `master` and see if you can decrypt files encrypted with the GUI?

**Comment by spieglt** [comment]
@logix2 Tagging you on this one as well in case you didn't see, thanks for following up on the other issue.

**Comment by logix2** [comment]
This one is fixed as well, thank you!

**Comment by spieglt** [comment]
Thank you!

**Comment by spieglt** [comment]
Thank you!
