### ISSUE TITLE
Can't run on Linux

### ISSUE THREAD

**Issue by arnauldb** [spieglt/Cloaker#4]
Hello,

When trying to run the .run file on Linux Mint Sylvia 18.3 I have this error:

>  $  ./Cloaker.run
> ./Cloaker.run: error while loading shared libraries: libicui18n.so.60: cannot open shared object file: No such file or directory

Thank you.

**Comment by spieglt** [comment]
Hmm, seems like you're on an older version of libicu than the version of Ubuntu I built with. Can you possibly try installing that version with `sudo apt install libicu60`?

**Comment by arnauldb** [comment]
I have this error now:

> ./Cloaker.run
> ./Cloaker.run: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./Cloaker.run)

**Comment by spieglt** [comment]
So there are probably several libraries for which Cloaker is trying to find a newer version than what's on your system. As far as I know, the only solutions are to upgrade to Mint 19 or compile from source on your machine. I don't have a computer with Mint 18.3 anymore unfortunately.

**Comment by arnauldb** [comment]
I will do a fresh install of Mint 19 soon anyway. Thank you.

**Comment by spieglt** [comment]
Thank you for your interest! I'll let you know if I think of anything else.
