### ISSUE TITLE
Cloaker 2.1 Not Working Windows 7

### ISSUE THREAD

**Issue by evennotodd** [spieglt/Cloaker#5]
I was able to encrypt a zip file fine on my Mac and then I went to test it and see if I could decrypt in on my Windows 7 laptop. For some reason Cloaker wouldn't even open on it even after it asked me if I wanted to run the file. How can I fix this or when will the next release be sent out with this fixed (if it's a known bug)?

**Comment by spieglt** [comment]
@evennotodd Did it give you the Windows Smart Screen warning? If so, you'll have to click "More Info" and then "Run anyway."

**Comment by spieglt** [comment]
Any screenshots or gifs of the process might also be helpful.

**Comment by spieglt** [comment]
Ah, actually, it was built on Windows 10 and I haven't tested it on Windows 7 at all as I don't have a Windows 7 machine anymore. It might just not work on there at all, come to think of it. I may be able to put one together but it'll take a while.

**Comment by spieglt** [comment]
You could also try the CLI version, it may just not work on Windows 7 because of Qt dependency mismatches.

**Comment by evennotodd** [comment]
For any screens that popped up (I’m not sure which ones did) I hit run and I also tried to run as admin. It shouldn’t be a huge issue as I won’t be running Windows 7 come January and I shouldn’t need to decrypt those files when I’m away from my Macs or a Windows 10 machine (hopefully). I did get the 1st release to run on Windows 7 though it wasn’t of much use to me since I try to encrypt with the latest versions.

**Comment by spieglt** [comment]
That makes sense as the first version was built as a native Windows app rather than with Qt. Unfortunately, files encrypted with versions 2.0+ can't be decrypted by version 1.0. I'll let you know if I get a Windows 7 setup going, but otherwise, please use the CLI version or use version 1.1 on both sides. Thank you for your interest and feedback, and sorry for the inconvenience.

**Comment by evennotodd** [comment]
Ok. I can use 1.1 on both sides until I upgrade. Thanks!

**Comment by evennotodd** [comment]
Can 1.1 files be decrypted in versions 2 and beyond?

**Comment by spieglt** [comment]
Yes! Though they'll need to have the `.cloaker` extension.

**Comment by evennotodd** [comment]
Ok. Thanks again!
