### ISSUE TITLE
Ubuntu 20.04 with newer libicu library

### ISSUE THREAD

**Issue by SoftExpert** [spieglt/Cloaker#8]
Hello,

Since upgrading to Ubuntu 20.04, Cloaker does not work any longer - it throws exception related to libicu version.
The version that comes with Ubuntu 20.04 is 66, but the version with which the binaries are compiled is 60.
I tried first to create symlinks to simulate an older version but internal functions include a version in their name:
`./Cloaker_linux: symbol lookup error: ./Cloaker_linux: undefined symbol: ucal_close_60`
Is it possible to provide a prebuilt version for Ubuntu 20.04, please?

Thank you in advance for your help!

Best regards,
SoftExpert

**Comment by spieglt** [comment]
Yes! I've upgraded to Ubuntu 20, still trying to work out some kinks after compiling Qt 5.15 statically, but should have it before too long and will let you know here.

**Comment by spieglt** [comment]
Okay, it's on the releases page. Try it out: https://github.com/spieglt/Cloaker/releases/download/v3.0/cloaker_ubuntu20

**Comment by SoftExpert** [comment]
Thank you, it works !
I tried to compile the code from repository with the latest Qt Creator and Qt 5.15.0, and it was pretty straightforward ; when building with the Release profile, the resulting binary is really small:
![image](https://user-images.githubusercontent.com/1254018/91543888-2effde80-e91f-11ea-9f46-5b82c770a301.png)

**Comment by spieglt** [comment]
Awesome! Yeah, compiling dynamically is easier and gives smaller binaries, but those binaries won't run on a machine without the libraries from your Qt installation, whereas the statically linked version should run on just stock Ubuntu 20 without having to install anything. Thanks for bringing the issue to my attention and for using Cloaker!

**Comment by spieglt** [comment]
@SoftExpert I realized I was being dumb and the dynamically linked binaries are more portable on Linux because most distros are going to have Qt libs installed, like you were saying, even if they don't have Qt Creator. There's now just one Linux binary in the new release.
